# Generated by Django 5.1.4 on 2025-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldUrlRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.CharField(help_text='Old PHP URL slug without .php', max_length=255, unique=True)),
                ('new_slug', models.CharField(help_text='New URL slug for redirection', max_length=255)),
                ('url_type', models.CharField(choices=[('category', 'Category'), ('product', 'Product'), ('blog', 'Blog'), ('news', 'News')], help_text='Type of URL', max_length=50)),
            ],
        ),
    ]
