# Generated by Django 5.1.4 on 2025-03-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldurlredirect',
            name='url_type',
            field=models.CharField(choices=[('category', 'Category'), ('product', 'Product')], help_text='Type of URL', max_length=50),
        ),
    ]
