# Generated by Django 5.1.4 on 2025-03-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_dashboard', '0002_alter_oldurlredirect_url_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldurlredirect',
            name='url_type',
            field=models.CharField(choices=[('category', 'Category'), ('product', 'Product'), ('news', 'News'), ('blog', 'Blog'), ('projects', 'Projects')], help_text='Type of URL', max_length=50),
        ),
    ]
