version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - django-db-data:/var/lib/mysql
    networks:
      - django-network
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  django:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django-static:/var/lib/django/static
      - django-media:/var/lib/django/media
      - ../photoproject:/opt/django/django_project/photoproject:ro
      - ../requirements.txt:/opt/django/django_project/requirements.txt:ro
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=photoproject.settings
      - PYTHONOPTIMIZE=2
      - LANG=C.UTF-8
      - TZ=Asia/Kolkata
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8001:8001"
    networks:
      - django-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/django.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - django-static:/var/lib/django/static
      - django-media:/var/lib/django/media
    depends_on:
      - django
    networks:
      - django-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - .env
    environment:
      - PMA_HOST=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - django-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  django-network:
    driver: bridge

volumes:
  django-db-data:
  django-static:
  django-media:
