# Generated by Django 5.1.4 on 2025-05-15 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_adminrequestquote_adminrequestquoteitem'),
        ('catalog', '0013_alter_datasheet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='datasheet',
            field=models.ForeignKey(blank=True, help_text='Optional reference to a datasheet for the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_items', to='catalog.datasheet'),
        ),
    ]
