# Generated by Django 5.1.4 on 2025-06-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_listitem_datasheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title for administrative purposes', max_length=200)),
                ('banner_type', models.CharField(choices=[('slider', 'Slider Banner'), ('about', 'About Banner'), ('sustainability', 'Sustainability Banner')], help_text='Type of banner', max_length=20)),
                ('image', models.ImageField(help_text='Banner image', upload_to='banners/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for image accessibility', max_length=200)),
                ('url', models.CharField(blank=True, help_text='URL for banner link', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance (only applies to slider banners)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is currently active')),
                ('meta_title', models.CharField(blank=True, help_text='Meta title for SEO (max 60 characters)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO (max 160 characters)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Meta keywords for SEO (comma-separated)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['banner_type', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('office_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('regional', 'Regional Office'), ('branch', 'Branch Office')], max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Office_locations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
