# Generated by Django 5.1.4 on 2025-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_banner_officelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officelocation',
            name='office_type',
        ),
        migrations.AddField(
            model_name='officelocation',
            name='office_country',
            field=models.CharField(blank=True, choices=[('bh', 'Kingdom of Bahrain'), ('qa', 'State of Qatar'), ('ae', 'United Arab Emirates'), ('om', 'Sultanate of Oman'), ('ye', 'Republic of Yemen'), ('sa', 'Kingdom of Saudi Arabia'), ('ir', 'Islamic Republic of Iran'), ('kw', 'State of Kuwait'), ('eg', 'Arab Republic of Egypt'), ('jo', 'Hashemite Kingdom of Jordan'), ('sy', 'Syrian Arab Republic')], max_length=20, null=True),
        ),
    ]
