# Generated by Django 5.1.4 on 2025-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_remove_officelocation_office_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officelocation',
            name='office_country',
            field=models.CharField(blank=True, choices=[('Bahrain', 'Bahrain'), ('Qatar', 'Qatar'), ('United Arab Emirates', 'United Arab Emirates'), ('Oman', 'Oman'), ('Yemen', 'Yemen'), ('Saudi Arabia', 'Saudi Arabia'), ('Iran', 'Iran'), ('Kuwait', 'Kuwait'), ('Egypt', 'Egypt'), ('Jordan', 'Jordan'), ('Syria', 'Syria')], max_length=20, null=True),
        ),
    ]
