# Generated by Django 5.1.4 on 2025-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_alter_officelocation_office_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='partnership_type',
            field=models.CharField(blank=True, choices=[('Strategic Partner', 'Strategic Partner'), ('Premier Partner', 'Premier Partner'), ('Preferred Partner', 'Preferred Partner'), ('Master Partner', 'Master Partner'), ('General Partner', 'General Partner')], max_length=50, null=True),
        ),
    ]
