# Generated by Django 5.1.4 on 2025-04-28 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_adminuser_seomanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('partner_company_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('partnership_level', models.CharField(choices=[('BRONZE', 'Bronze Partner'), ('SILVER', 'Silver Partner'), ('GOLD', 'Gold Partner')], default='BRONZE', max_length=20)),
                ('partnership_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
            bases=('user_account.user',),
        ),
    ]
