# Generated by Django 5.1.4 on 2025-02-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_alt',
            field=models.CharField(blank=True, help_text='Alt text for the banner image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL to avoid duplicate content', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_alt',
            field=models.CharField(blank=True, help_text='Alt text for the icon image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Short description for search engine snippets', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO-friendly title (if different from name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='side_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the side image', max_length=255, null=True),
        ),
    ]
