# Generated by Django 5.1.4 on 2025-02-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_banner_alt_category_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the category name', max_length=255, unique=True),
        ),
    ]
