# Generated by Django 5.1.4 on 2025-02-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='meta_title',
            new_name='meta_tags',
        ),
    ]
