# Generated by Django 5.1.4 on 2025-02-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_meta_title_category_meta_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the main image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Short description for search engine snippets', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tags',
            field=models.CharField(blank=True, help_text='SEO-friendly title (if different from name)', max_length=255, null=True),
        ),
    ]
