# Generated by Django 5.1.4 on 2025-04-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_name',
            field=models.CharField(blank=True, help_text='Alternative name for SEO purposes', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_name',
            field=models.CharField(blank=True, help_text='Alternative name for SEO purposes', max_length=255, null=True),
        ),
    ]
