# Generated by Django 5.1.4 on 2025-05-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_seo_name_product_seo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_marked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when product was marked as featured', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Flag to mark product as featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_latest',
            field=models.BooleanField(default=False, help_text='Flag to mark product as latest'),
        ),
        migrations.AddField(
            model_name='product',
            name='latest_marked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when product was marked as latest', null=True),
        ),
    ]
