# Generated by Django 5.1.4 on 2025-05-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_datasheet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheet',
            options={'ordering': ['name']},
        ),
    ]
