# Generated by Django 5.1.4 on 2025-05-15 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_datasheet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depth (cm/inches)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height (cm/inches)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='size',
            field=models.CharField(blank=True, help_text='Size (e.g., 5 MB, 10x10x5 cm)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width (cm/inches)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
