# Generated by Django 5.1.4 on 2025-05-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_datasheet_depth_datasheet_height_datasheet_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='include_size_dimensions',
            field=models.BooleanField(default=False, help_text='Check to include size and dimension details'),
        ),
    ]
