# Generated by Django 5.1.4 on 2025-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_datasheet_include_size_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='depth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
