# Generated by Django 5.1.4 on 2025-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_datasheet_depth_alter_datasheet_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='include_part_number',
            field=models.BooleanField(default=False, help_text='Check to include part_number or reference number'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='part_number',
            field=models.CharField(blank=True, help_text='Product part number or reference number', max_length=50, null=True),
        ),
    ]
