# Generated by Django 5.1.4 on 2025-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_datasheet_include_part_number_datasheet_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(blank=True, choices=[('Nos', 'Nos'), ('305 Mtr Box', '305 Mtr Box'), ('500 Mtr Box', '500 Mtr Box'), ('305 Mtr Roll', '305 Mtr Roll'), ('500 Mtr Roll', '500 Mtr Roll'), ('Mtr', 'Mtr')], help_text='Measurement of the product', max_length=50, null=True),
        ),
    ]
