name: Deploy Django App on AWS Server

on:
  workflow_dispatch: # Allows manual triggering
  workflow_run:
    workflows: ["Pull Code to AWS Server"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if the pull-code workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 50.19.222.82 >> ~/.ssh/known_hosts

      - name: Deploy Django app on server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@50.19.222.82 << 'EOF'
            /home/ubuntu/django_project/deploy.sh
          EOF
