name: Pull Code to AWS Server

on:
  push:
    branches:
      - main

jobs:
  pull-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 50.19.222.82 >> ~/.ssh/known_hosts

      - name: Pull code to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@50.19.222.82 << 'EOF'
            /home/ubuntu/django_project/pull_code.sh
          EOF

